<a href="https://colab.research.google.com/github/AlvinDefanno/Pyton-for-Database/blob/main/belajar3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import sys
sys.path

['',
 '/content',
 '/env/python',
 '/usr/lib/python37.zip',
 '/usr/lib/python3.7',
 '/usr/lib/python3.7/lib-dynload',
 '/usr/local/lib/python3.7/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/local/lib/python3.7/dist-packages/IPython/extensions',
 '/root/.ipython']

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame()

Empty DataFrame
Columns: []
Index: []

In [ ]:
a = first_df=pd.DataFrame({'person':['oranga','orangb'],'pay':[50,30]})
a

   person  pay
0  oranga   50
1  orangb   30

In [ ]:
a = first_df=pd.DataFrame({'person':['oranga','orangb'],'pay':[50,30]}, index=['produk_1','produk_2'])
a

          person  pay
produk_1  oranga   50
produk_2  orangb   30

In [ ]:
pd.Series([1,2,3,4,5])

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
pd.Series([1,2,3, 4,5], index=['Sales 1','Sales 2','Sales3', 'Sales 4','Sales5'])

Sales 1    1
Sales 2    2
Sales3     3
Sales 4    4
Sales5     5
dtype: int64

In [ ]:
import pandas as pd
df = pd.read_csv("/Pandas/iris_concat_1.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df.shape

(89, 6)

In [ ]:
len(df)

89

In [ ]:
df.head(6)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
5   6            5.4           3.9            1.7           0.4  Iris-setosa

In [ ]:
df.tail(6)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
           ...
84    Iris-versicolor
85    Iris-versicolor
86    Iris-versicolor
87    Iris-versicolor
88    Iris-versicolor
Name: Species, Length: 89, dtype: object

In [ ]:
df['Species'][88]

'Iris-versicolor'

In [ ]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
df['PetalLengthCm'].dtype

dtype('float64')

In [ ]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [ ]:
df['Species'].describe()

count              89
unique              2
top       Iris-setosa
freq               50
Name: Species, dtype: object

In [ ]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor'], dtype=object)

In [ ]:
df['Species'].nunique()

2

In [ ]:
df['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    39
Name: Species, dtype: int64

In [ ]:
df.count()

Id               89
SepalLengthCm    87
SepalWidthCm     89
PetalLengthCm    89
PetalWidthCm     89
Species          89
dtype: int64

In [ ]:
df.groupby(by='Species').sum(id)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm
Species,,,,,
Iris-setosa,1275,239.7,170.9,73.2,12.2
Iris-versicolor,2730,234.9,108.7,168.7,52.7

In [ ]:
df.iloc[5]

Id                         6
SepalLengthCm            5.4
SepalWidthCm             3.9
PetalLengthCm            1.7
PetalWidthCm             0.4
Species          Iris-setosa
Name: 5, dtype: object

In [ ]:
df.iloc[:,3]

0     1.4
1     1.4
2     1.3
3     1.5
4     1.4
     ...
84    4.5
85    4.5
86    4.7
87    4.4
88    4.1
Name: PetalLengthCm, Length: 89, dtype: float64

In [ ]:
df.iloc[1:3,:]

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa

In [ ]:
df.loc[33,'Species']

'Iris-setosa'

In [ ]:
df.loc[5:,['Species','PetalWidthCm']]

            Species  PetalWidthCm
5       Iris-setosa           0.4
6       Iris-setosa           0.3
7       Iris-setosa           0.2
8       Iris-setosa           0.2
9       Iris-setosa           0.1
..              ...           ...
84  Iris-versicolor           1.5
85  Iris-versicolor           1.6
86  Iris-versicolor           1.5
87  Iris-versicolor           1.3
88  Iris-versicolor           1.3

[84 rows x 2 columns]

In [ ]:
df.set_index('Id')

    SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
Id
1             5.1           3.5            1.4           0.2      Iris-setosa
2             4.9           3.0            1.4           0.2      Iris-setosa
3             4.7           3.2            1.3           0.2      Iris-setosa
4             4.6           3.1            1.5           0.2      Iris-setosa
5             5.0           3.6            1.4           0.2      Iris-setosa
..            ...           ...            ...           ...              ...
85            5.4           3.0            4.5           1.5  Iris-versicolor
86            6.0           3.4            4.5           1.6  Iris-versicolor
87            6.7           3.1            4.7           1.5  Iris-versicolor
88            6.3           2.3            4.4           1.3  Iris-versicolor
89            5.6           3.0            4.1           1.3  Iris-versicolor

[89 rows x 5 columns]

In [ ]:
df['Species'] == 'Iris-versicolor'

0     False
1     False
2     False
3     False
4     False
      ...
84     True
85     True
86     True
87     True
88     True
Name: Species, Length: 89, dtype: bool

In [ ]:
df[(df['SepalLengthCm'] > 3) & (df['Species'] == 'Iris-versicolor')]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df[df['Species'].isin(['Iris-versicolor','Irisvirginica'])]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
50,51,7.0,3.2,4.7,1.4,Iris-versicolor
51,52,6.4,3.2,4.5,1.5,Iris-versicolor
52,53,6.9,3.1,4.9,1.5,Iris-versicolor
53,54,5.5,2.3,4.0,1.3,Iris-versicolor
54,55,6.5,2.8,4.6,1.5,Iris-versicolor
55,56,5.7,2.8,4.5,1.3,Iris-versicolor
56,57,6.3,3.3,4.7,1.6,Iris-versicolor
57,58,4.9,2.4,3.3,1.0,Iris-versicolor
58,59,6.6,2.9,4.6,1.3,Iris-versicolor
59,60,5.2,2.7,3.9,1.4,Iris-versicolor
60,61,5.0,2.0,3.5,1.0,Iris-versicolor
61,62,5.9,3.0,4.2,1.5,Iris-versicolor
62,63,6.0,2.2,4.0,1.0,Iris-versicolor
63,64,6.1,2.9,4.7,1.4,Iris-versicolor
64,65,5.6,2.9,3.6,1.3,Iris-versicolor
65,66,6.7,3.1,4.4,1.4,Iris-versicolor
66,67,5.6,3.0,4.5,1.5,Iris-versicolor
67,68,5.8,2.7,4.1,1.0,Iris-versicolor
68,69,6.2,2.2,4.5,1.5,Iris-versicolor
69,70,5.6,2.5,3.9,1.1,Iris-versicolor
70,71,5.9,3.2,4.8,1.8,Iris-versicolor
71,72,6.1,2.8,4.0,1.3,Iris-versicolor
72,73,6.3,2.5,4.9,1.5,Iris-versicolor
73,74,6.1,2.8,4.7,1.2,Iris-versicolor
74,75,6.4,2.9,4.3,1.3,Iris-versicolor
75,76,6.6,3.0,4.4,1.4,Iris-versicolor
76,77,6.8,2.8,4.8,1.4,Iris-versicolor
77,78,6.7,3.0,5.0,1.7,Iris-versicolor
78,79,6.0,2.9,4.5,1.5,Iris-versicolor
79,80,5.7,2.6,3.5,1.0,Iris-versicolor
80,81,5.5,2.4,3.8,1.1,Iris-versicolor
81,82,5.5,2.4,3.7,1.0,Iris-versicolor
82,83,5.8,2.7,3.9,1.2,Iris-versicolor
83,84,6.0,2.7,5.1,1.6,Iris-versicolor
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
filter = df['SepalLengthCm'] > 4
df.where(filter)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.140
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.140
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.130
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.150
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.140
...,...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor,3.375
85,86,6.0,3.4,4.5,1.6,Iris-versicolor,3.600
86,87,6.7,3.1,4.7,1.5,Iris-versicolor,3.525
87,88,6.3,2.3,4.4,1.3,Iris-versicolor,2.860
88,89,5.6,3.0,4.1,1.3,Iris-versicolor,2.665

In [ ]:
dataframe_1 = pd.DataFrame([['a', 1], ['b', 2]],columns=['letter', 'number'])
dataframe_1

  letter  number
0      a       1
1      b       2

In [ ]:
dataframe_2 = pd.DataFrame([['c', 4], ['a', 4]],columns=['letter', 'number'])
dataframe_2

  letter  number
0      c       4
1      a       4

In [ ]:
pd.concat([dataframe_1,dataframe_2],axis =0)

  letter  number
0      a       1
1      b       2
0      c       4
1      a       4

In [ ]:
pd.concat([dataframe_1,dataframe_2],axis =1)

  letter  number letter  number
0      a       1      c       4
1      b       2      a       4

In [ ]:
dataframe_1=pd.DataFrame({'key': ['K0','K1','K2','K3','K4','K5'],"A" :['A0','A1','A2','A3','A4','A5']})
dataframe_1

  key   A
0  K0  A0
1  K1  A1
2  K2  A2
3  K3  A3
4  K4  A4
5  K5  A5

In [ ]:
dataframe_2=pd.DataFrame({'key': ['K0','K1','K2'],"B": ['B0','B1','B2']})
dataframe_2

  key   B
0  K0  B0
1  K1  B1
2  K2  B2

In [ ]:
dataframe_1.join(dataframe_2,how='left',lsuffix='_1',rsuffix='_2')

  key_1   A key_2    B
0    K0  A0    K0   B0
1    K1  A1    K1   B1
2    K2  A2    K2   B2
3    K3  A3   NaN  NaN
4    K4  A4   NaN  NaN
5    K5  A5   NaN  NaN

In [ ]:
df['Species'].astype(str)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
           ...
84    Iris-versicolor
85    Iris-versicolor
86    Iris-versicolor
87    Iris-versicolor
88    Iris-versicolor
Name: Species, Length: 89, dtype: object

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    2
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89 entries, 0 to 88
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             89 non-null     int64
 1   SepalLengthCm  87 non-null     float64
 2   SepalWidthCm   89 non-null     float64
 3   PetalLengthCm  89 non-null     float64
 4   PetalWidthCm   89 non-null     float64
 5   Species        89 non-null     object
dtypes: float64(4), int64(1), object(1)
memory usage: 4.3+ KB

In [ ]:
a= df['SepalLengthCm']=df['SepalLengthCm'].fillna(df['SepalLengthCm'].mean())
a

0     5.1
1     4.9
2     4.7
3     4.6
4     5.0
     ...
84    5.4
85    6.0
86    6.7
87    6.3
88    5.6
Name: SepalLengthCm, Length: 89, dtype: float64

In [ ]:
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df = df.drop_duplicates()
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df.drop(0, axis = 0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
5,6,5.4,3.9,1.7,0.4,Iris-setosa
...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df.drop([0,1,2,3,4], axis = 0)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
5,6,5.4,3.9,1.7,0.4,Iris-setosa
6,7,4.6,3.4,1.4,0.3,Iris-setosa
7,8,5.0,3.4,1.5,0.2,Iris-setosa
8,9,4.4,2.9,1.4,0.2,Iris-setosa
9,10,4.9,3.1,1.5,0.1,Iris-setosa
...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor
85,86,6.0,3.4,4.5,1.6,Iris-versicolor
86,87,6.7,3.1,4.7,1.5,Iris-versicolor
87,88,6.3,2.3,4.4,1.3,Iris-versicolor
88,89,5.6,3.0,4.1,1.3,Iris-versicolor

In [ ]:
df.sort_values(by="SepalWidthCm", ascending=True)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
60,61,5.000000,2.0,3.5,1.0,Iris-versicolor
62,63,6.000000,2.2,4.0,1.0,Iris-versicolor
68,69,6.200000,2.2,4.5,1.5,Iris-versicolor
53,54,5.500000,2.3,4.0,1.3,Iris-versicolor
87,88,6.300000,2.3,4.4,1.3,Iris-versicolor
...,...,...,...,...,...,...
5,6,5.400000,3.9,1.7,0.4,Iris-setosa
14,15,5.800000,4.0,1.2,0.2,Iris-setosa
32,33,5.200000,4.1,1.5,0.1,Iris-setosa
33,34,5.455172,4.2,1.4,0.2,Iris-setosa
15,16,5.700000,4.4,1.5,0.4,Iris-setosa

In [ ]:
df.sort_values(by="SepalWidthCm", ascending=True).reset_index()

,index,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,60,61,5.000000,2.0,3.5,1.0,Iris-versicolor
1,62,63,6.000000,2.2,4.0,1.0,Iris-versicolor
2,68,69,6.200000,2.2,4.5,1.5,Iris-versicolor
3,53,54,5.500000,2.3,4.0,1.3,Iris-versicolor
4,87,88,6.300000,2.3,4.4,1.3,Iris-versicolor
...,...,...,...,...,...,...,...
84,5,6,5.400000,3.9,1.7,0.4,Iris-setosa
85,14,15,5.800000,4.0,1.2,0.2,Iris-setosa
86,32,33,5.200000,4.1,1.5,0.1,Iris-setosa
87,33,34,5.455172,4.2,1.4,0.2,Iris-setosa
88,15,16,5.700000,4.4,1.5,0.4,Iris-setosa

In [ ]:
df["PetalArea"]= 0.5 * df["PetalWidthCm"] * df["PetalLengthCm"]
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,PetalArea
0,1,5.1,3.5,1.4,0.2,Iris-setosa,0.140
1,2,4.9,3.0,1.4,0.2,Iris-setosa,0.140
2,3,4.7,3.2,1.3,0.2,Iris-setosa,0.130
3,4,4.6,3.1,1.5,0.2,Iris-setosa,0.150
4,5,5.0,3.6,1.4,0.2,Iris-setosa,0.140
...,...,...,...,...,...,...,...
84,85,5.4,3.0,4.5,1.5,Iris-versicolor,3.375
85,86,6.0,3.4,4.5,1.6,Iris-versicolor,3.600
86,87,6.7,3.1,4.7,1.5,Iris-versicolor,3.525
87,88,6.3,2.3,4.4,1.3,Iris-versicolor,2.860
88,89,5.6,3.0,4.1,1.3,Iris-versicolor,2.665

In [ ]:
df.rename(columns = {'SepalLengthCm': 'Data_1','SepalWidthCm': 'Data_2', 'PetalLengthCm':'Data_3','PetalWidthCm':'Data_4','Species':'Data_5','PetalArea':'Data_6'})

    Id  Data_1  Data_2  Data_3  Data_4           Data_5  Data_6
0    1     5.1     3.5     1.4     0.2      Iris-setosa   0.140
1    2     4.9     3.0     1.4     0.2      Iris-setosa   0.140
2    3     4.7     3.2     1.3     0.2      Iris-setosa   0.130
3    4     4.6     3.1     1.5     0.2      Iris-setosa   0.150
4    5     5.0     3.6     1.4     0.2      Iris-setosa   0.140
..  ..     ...     ...     ...     ...              ...     ...
84  85     5.4     3.0     4.5     1.5  Iris-versicolor   3.375
85  86     6.0     3.4     4.5     1.6  Iris-versicolor   3.600
86  87     6.7     3.1     4.7     1.5  Iris-versicolor   3.525
87  88     6.3     2.3     4.4     1.3  Iris-versicolor   2.860
88  89     5.6     3.0     4.1     1.3  Iris-versicolor   2.665

[89 rows x 7 columns]